language: python
python:
- '2.7'

deploy:
  provider: pypi
  user: numenta
  password:
    secure: Csy43XEGiWWZFK+YVlVNQk3Wm0OFQPM9IJGDuxrnI8nPuoXcMiQ8z23dcwpx/jaEQqYwSKViCordlgOgGLj6usINHQZfhv9SzmNlRWDYxrBLBMa76jAmpeX8bwzYWc+g9E39JrxdNSGUk011ROZVXhuEkY/ifuIjUz2jtXTzgco=
  on:
    repo: numenta/pycept

install:
- pip install requests
- pip install nose
- pip install coverage
- pip install httpretty

script:
- nosetests --with-coverage

after_success:
- pip install python-coveralls
- coveralls
