language: python
python:
- '2.7'

install:
- pip install requests
- pip install nose
- pip install coverage
- pip install httpretty

script:
- nosetests --with-coverage

after_success:
- pip install python-coveralls
- coveralls
