language: python
python:
- '2.7'

deploy:
  provider: pypi
  user: numenta
  password:
    secure: MyAxE9A0x39COGH60r5cbexXQh/KCNw8b47a6nRw6X8buHit7Uc/PawzV6BHyziuez1IfrGDdIMBFZMnmHrS+XjbtBrknCQTeqP3cOvJZePe90o+puF21TVdtyJuat7myWcge5+bsdjwaAGrHIp05H8zaxgO2/LX7Y3xyLmwy8A=
  on:
    repo: numenta/pycept

install:
- pip install requests
- pip install nose
- pip install coverage
- pip install httpretty

script:
- nosetests --with-coverage

after_success:
- pip install python-coveralls
- coveralls
